<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Benchmarks</RootNamespace>
    <RollForward>Major</RollForward>
    <TieredCompilation>false</TieredCompilation>
    <Optimize>true</Optimize>
    <AppendTargetFrameworkToOutputPath>False</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\bin\$(Configuration)\net8\Kni\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="nkast.Xna.Framework" Version="4.2.9001" />
  </ItemGroup>
    <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
  </ItemGroup>
  <Import Project="..\Benchmarks.Shared\Benchmarks.Shared.projitems" Label="Shared" />
</Project>
