for /L %%A in (1001,1,1064) do copy "BenchmarksContent\BenchmarksSounds\Sound.wav" "BenchmarksContent\BenchmarksSounds\Sound%%A.wav"
for /L %%A in (1001,1,1064) do copy "BenchmarksContent\BenchmarksFonts\Font.spritefont" "BenchmarksContent\BenchmarksFonts\Font%%A.spritefont"
for /L %%A in (1001,1,1064) do copy "BenchmarksContent\BenchmarksTextures\Tx.png" "BenchmarksContent\BenchmarksTextures\Tx%%A.png"
for /L %%A in (1001,1,1064) do copy "BenchmarksContent\BenchmarksEffects\Effect.fx" "BenchmarksContent\BenchmarksEffects\Effect%%A.fx"
for /L %%A in (1001,1,1064) do copy "BenchmarksContent\BenchmarksModels\Model.fbx" "BenchmarksContent\BenchmarksModels\Model%%A.fbx"
