<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Benchmarks</RootNamespace>
    <RollForward>Major</RollForward>
    <TieredCompilation>false</TieredCompilation>
    <Optimize>true</Optimize>
    <AppendTargetFrameworkToOutputPath>False</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\bin\$(Configuration)\net10\Fna\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Benchmarks.Shared\Program.cs" Link="Program.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Benchmarks.Shared\Benchmarks.Fna.Lib.csproj" />
  </ItemGroup>
</Project>
