<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Benchmarks</RootNamespace>
    <RollForward>Major</RollForward>
    <TieredCompilation>false</TieredCompilation>
    <Optimize>true</Optimize>
    <AppendTargetFrameworkToOutputPath>False</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\bin\$(Configuration)\net8\Fna\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="FNA">
      <HintPath>..\..\ContentBenchmarks\Benchmarks.Fna.OpenGL\FNA23.07\net6.0\FNA.dll</HintPath>
    </Reference>
  </ItemGroup>
  <Import Project="..\Benchmarks.Shared\Benchmarks.Shared.projitems" Label="Shared" />
</Project>
